apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: pj6hfkurc-dotnet-basic
  janus-idp.io/tekton: pj6hfkurc-dotnet-basic
  backstage.io/kubernetes-id: pj6hfkurc-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: pj6hfkurc-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
